routes:
  - input:
      plugin: metrics_pull
      config:
        # URL, на который будем ходить за данными метрик.
        url: http://localhost:9090/metrics  # обязательный

        # Формат получаемых сообщений. В настоящий момент поддерживается только значение prometheus.
        format:  # обязательный
          # Входящие сообщения имеют формат prometheus (https://github.com/prometheus/docs/blob/master/content/docs/instrumenting/exposition_formats.md).
          prometheus: {}

        # Периодичность опроса источника данных.
        # Моменты запуска выровнены по сетке размера poll_period, начиная с unix epoch.
        poll_period: 15s  # необязательный, по умолчанию 15 секунд

        # Неймсмпейс, в который нужно поместить метрики.
        # Если указан, будет добавлен префиксом с точкой к имени всех метрик.
        namespace: null  # необязательный, по умолчанию не задан

        # Число повторых попыток, если запрос завершился с ошибкой.
        retry_count: 0  # необязательный, по умолчанию 0

        # Задержка между повторными попытками.
        retry_delay: 1s  # необязательный, по умолчанию 1 секунда

        # Таймаут запроса, включая все повторые попытки.
        timeout: 5s  # необязательный, по умолчанию 5 секунд

        # Заголовки, которые нужно добавить к запросу.
        headers:  # необязательный, по умолчанию не задан
          h1: v1
          h2: v2

        # Имена заголовков HTTP-ответа, которые нужно сохранить в метаданных сообщения.
        capture_response_headers: []  # необязательный, по умолчанию не задан

        # HTTP-метод, который нужно использовать в запросе.
        # Возможные значения: GET, POST.
        http_method: GET  # необязательный, по умолчанию GET
    channel:
      channel_ref:
        name: yc_metrics_channel