name: Destroy CatGPT

on: [ workflow_dispatch ]

env:
  APP_IMAGE_TAG: cr.yandex/${{ secrets.YC_CR_ID }}/catgpt:latest
  TF_ROOT: ./terraform

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    environment: STAND
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Init
        run: |
          terraform version
          cd ${{ env.TF_ROOT }} && echo '${{ secrets.YC_SA_KEY }}' > sa-key.json
          terraform init \
            -backend-config "bucket=${{ secrets.TF_VAR_S3_BUCKET }}" \
            -backend-config "key=${{ secrets.TF_VAR_S3_KEY }}" \
            -backend-config "access_key=${{ secrets.TF_VAR_S3_ACCESS_KEY }}" \
            -backend-config "secret_key=${{ secrets.TF_VAR_S3_SECRET_KEY }}"

      - name: Destroy
        run: |
          terraform version
          cd ${{ env.TF_ROOT }}
          terraform destroy --auto-approve \
            -var TF_VAR_FOLDER_ID="${{ secrets.TF_VAR_FOLDER_ID }}" \
            -var TF_VAR_APP_IMAGE_TAG="${{ env.APP_IMAGE_TAG }}" \
            -var TF_VAR_SSH_PUB="${{ secrets.TF_VAR_SSH_PUB }}"
